-- CreateTable
CREATE TABLE IF NOT EXISTS `bihar_ula_site_survey` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` VARCHAR(100) NOT NULL,
    `ca_no` VARCHAR(100) NOT NULL,
    `ca_name` VARCHAR(100) NOT NULL,
    `state` VARCHAR(100) NOT NULL,
    `district` VARCHAR(255) NULL,
    `block` VARCHAR(255) NULL,
    `panchayat` VARCHAR(255) NULL,
    `village` VARCHAR(255) NULL,
    `survey_date` DATE NOT NULL,
    `beneficiary_name` VARCHAR(255) NOT NULL,
    `beneficiary_contact` VARCHAR(20) NOT NULL,
    `panel_one_img` VARCHAR(255) NULL,
    `panel_one_no` VARCHAR(255) NULL,
    `panel_two_img` VARCHAR(255) NULL,
    `panel_two_no` VARCHAR(255) NULL,
    `inverter_img` VARCHAR(255) NULL,
    `inverter_no` VARCHAR(255) NULL,
    `smart_meter_img` VARCHAR(255) NULL,
    `acdb_img` VARCHAR(255) NULL,
    `system_img` VARCHAR(255) NULL,
    `solar_meter_img` VARCHAR(255) NULL,
    `latitude` VARCHAR(50) NULL,
    `longitude` VARCHAR(50) NULL,
    `user_id` VARCHAR(50) NULL,
    `modification` VARCHAR(50) NULL,
    `solar_meter_img2` VARCHAR(255) NULL,
    `system_img2` VARCHAR(255) NULL,
    `latitude2` VARCHAR(50) NULL,
    `longitude2` VARCHAR(50) NULL,
    `user_id2` VARCHAR(50) NULL,
    `remarks` TEXT NULL,
    `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`),
    INDEX `bihar_ula_site_survey_company_id_idx`(`company_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
