-- CreateTable
CREATE TABLE `light_amcs` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `company_id` VARCHAR(100) NOT NULL,
    `user_id` VARCHAR(100) NOT NULL,
    `state` VARCHAR(100) NOT NULL,
    `district` VARCHAR(255) NULL,
    `block` VARCHAR(255) NULL,
    `panchayat` VARCHAR(255) NULL,
    `ward_no` VARCHAR(50) NULL,
    `volume` VARCHAR(100) NULL,
    `ssl_id` VARCHAR(100) NOT NULL,
    `unique_id` VARCHAR(255) NULL,
    `pole_no` VARCHAR(255) NULL,
    `amc_date` DATE NOT NULL,
    `next_amc_date` DATE NOT NULL,
    `period_start` DATE NOT NULL,
    `period_end` DATE NOT NULL,
    `quarter_no` INTEGER NOT NULL DEFAULT 1,
    `beneficiary_name` VARCHAR(255) NOT NULL,
    `beneficiary_contact` VARCHAR(20) NOT NULL,
    `light_working` VARCHAR(10) NOT NULL,
    `complaint_raised` TINYINT NOT NULL DEFAULT 0,
    `complaint_ref` VARCHAR(255) NULL,
    `image_1` VARCHAR(255) NULL,
    `image_2` VARCHAR(255) NULL,
    `remarks` TEXT NULL,
    `created_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP(0),

    INDEX `light_amcs_ssl_id_idx`(`ssl_id`),
    INDEX `light_amcs_company_id_idx`(`company_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
